### ISSUE TITLE
Ajax loading of tab content

### ISSUE THREAD

**Issue by htowens** [techiferous/tabulous#2]
Hi,

Just taking Tabulous for a spin at present, and I like the look of it.

Do you have any suggestions for a clean way to get the tabs loading their content on demand, via Ajax? I think this would give a much more RIA feel to my app.

Thanks for any pointers you can provide!

Henry.

**Comment by asada** [comment]
@nickl- Were you able to come up with some way of doing this with Tabulous? What path did you guys take?

**Comment by techiferous** [comment]
I've decided that tabulous' architecture is firmly in the server-side rendering world and should stay there.  I think we'd end up with a pretty complicated mess if we tried to force a server-side rendering tool to be something it's not.  Better just to make a new tool.  Also see https://github.com/techiferous/tabulous/blob/master/FUTURE.md
