### ISSUE TITLE
How can I have a particular subtab appear under more than one tab

### ISSUE THREAD

**Issue by svavantsa** [techiferous/tabulous#55]
Hi Wayne,

I have a situation. I have a subtab called Attachments that I want to appear under more than one tab. This is because, the attachments apply to more than one entity. When I simply repeat the attachments_subtab section under more than one tab in the tabs/tabulous.rb file, I am getting a runtime error stating that I can't have more than one tab with the same active_when condition. Is there a better way of doing this to avoid the error message?

**Comment by techiferous** [comment]
Hi @svavantsa,

Tabulous does not support this condition.  I would step back and consider that maybe you could arrange your navigation differently?  If attachments should be able to be navigated to in many different tabs, perhaps it should be pulled out to be its own main tab or even a permanent link next to the navbar.

In any case tabulous does not support this.  A work-around would be for these other subtabs to navigate to controllers that then redirect to the controller you want.  That's a rather hackish solution, though.

**Comment by svavantsa** [comment]
Hi Wayne,

Thank you for getting back to me. Let me consider your suggestions and I'll
let you know if I have any other concerns.
ᐧ


Thank You,

Surya Avantsa

How do they say my name? <http://vame.me/suryaavantsa>

**Comment by svavantsa** [comment]
Wayne,

I simply created another controller with a new name and inherited it from
the other controller I created first. That's it. It does every thing that
other did and at the same time, I am able to have it appear under multiple
tabs as subtabs.
ᐧ


Thank You,

Surya Avantsa
